name: ampareqrcodelinux
version: 1.0.0
summary: Ampare QR Code Creator
description: A Simple QR Code Creator For Linux
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  ampareqrcodelinux:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/ampareqrcodelinux
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: /home/juthawong/Documents/AmpareQRCodeLinux/dist/linux-unpacked
    after:
      - desktop-gtk2
